from PyQt5.QtWidgets import QDialog, QRadioButton

from Ui_Pipeline_Handler import *

class Pipeline_Handler(QDialog):
	"""docstring for Pipeline_Handler"""
	def __init__(self):
		super().__init__()
		self.ui = Ui_Dialog_Pipeline_Handler()
		self.ui.setupUi(self)

		self.flag_1 = True

		self.lista_Nodos = Lista_Nodos()
		self.cont_lista_Nodos_Inicio = 0

		self.list_cont_por_Nodos_Proceso = [0,0,0,0,0,0,0,0,0,0]
		self.cont_Capa_Proceso = 0

		self.lista_Capas_Nodos_Proceso = [
			[9, 10, 11, 12, 13, 14, 15, 16, 17],
			[18, 19, 20, 21, 22, 23, 24, 25, 26],
			[27, 28, 29, 30, 31, 32, 33, 34, 35],
			[36, 37, 38, 39, 40, 41, 42, 43, 44],
			[45, 46, 47, 48, 49, 50, 51, 52, 53],
			[54, 55, 56, 57, 58, 59, 60, 61, 62],
			[63, 64, 65, 66, 67, 68, 69, 70, 71],
			[72, 73, 74, 75, 76, 77, 78, 79, 80],
			[81, 82, 83, 84, 85, 86, 87, 88, 89],
			[90, 91, 92, 93, 94, 95, 96, 97, 98]
		]

		self.init_Disposition_Chooser()

		self.ui.pushButton_6.setEnabled(False)
		self.ui.pushButton_7.setEnabled(False)
		self.ui.pushButton_8.setEnabled(False)
		self.ui.pushButton_9.setEnabled(False)
		self.ui.pushButton.setEnabled(False)

		self.ui.pushButton_5.clicked.connect(self.adicionar_Nodo_Inicio)
		self.ui.pushButton_6.clicked.connect(self.eliminar_Nodo_Inicio)
		self.ui.pushButton_7.clicked.connect(self.adicionar_Nodo_Proceso)
		self.ui.pushButton_8.clicked.connect(self.eliminar_Nodo_Proceso)
		self.ui.pushButton_9.clicked.connect(self.adicionar_Capa_Proceso)
		self.ui.pushButton.clicked.connect(self.eliminar_Capa_Proceso)

    
	def init_Disposition_Chooser(self):
		self.ui.radioButton.hide()
		nodo_0 = Nodo(self.ui.radioButton)
		nodo_0.setId(0)
		self.lista_Nodos.adicionar(nodo_0)
		self.ui.radioButton_2.hide()
		nodo_1 = Nodo(self.ui.radioButton_2)
		nodo_1.setId(1)
		self.lista_Nodos.adicionar(nodo_1)
		self.ui.radioButton_3.hide()
		nodo_2 = Nodo(self.ui.radioButton_3)
		nodo_2.setId(2)
		self.lista_Nodos.adicionar(nodo_2)
		self.ui.radioButton_4.hide()
		nodo_3 = Nodo(self.ui.radioButton_4)
		nodo_3.setId(3)
		self.lista_Nodos.adicionar(nodo_3)
		self.ui.radioButton_5.hide()
		nodo_4 = Nodo(self.ui.radioButton_5)
		nodo_4.setId(4)
		self.lista_Nodos.adicionar(nodo_4)
		self.ui.radioButton_6.hide()
		nodo_5 = Nodo(self.ui.radioButton_6)
		nodo_5.setId(5)
		self.lista_Nodos.adicionar(nodo_5)
		self.ui.radioButton_7.hide()
		nodo_6 = Nodo(self.ui.radioButton_7)
		nodo_6.setId(6)
		self.lista_Nodos.adicionar(nodo_6)
		self.ui.radioButton_8.hide()
		nodo_7 = Nodo(self.ui.radioButton_8)
		nodo_7.setId(7)
		self.lista_Nodos.adicionar(nodo_7)
		self.ui.radioButton_9.hide()
		nodo_8 = Nodo(self.ui.radioButton_9)
		nodo_8.setId(8)
		self.lista_Nodos.adicionar(nodo_8)
		self.ui.radioButton_10.hide()
		nodo_9 = Nodo(self.ui.radioButton_10)
		nodo_9.setId(9)
		self.lista_Nodos.adicionar(nodo_9)
		self.ui.radioButton_11.hide()
		nodo_10 = Nodo(self.ui.radioButton_11)
		nodo_10.setId(10)
		self.lista_Nodos.adicionar(nodo_10)
		self.ui.radioButton_12.hide()
		nodo_11 = Nodo(self.ui.radioButton_12)
		nodo_11.setId(11)
		self.lista_Nodos.adicionar(nodo_11)
		self.ui.radioButton_13.hide()
		nodo_12 = Nodo(self.ui.radioButton_13)
		nodo_12.setId(12)
		self.lista_Nodos.adicionar(nodo_12)
		self.ui.radioButton_14.hide()
		nodo_13 = Nodo(self.ui.radioButton_14)
		nodo_13.setId(13)
		self.lista_Nodos.adicionar(nodo_13)
		self.ui.radioButton_15.hide()
		nodo_14 = Nodo(self.ui.radioButton_15)
		nodo_14.setId(14)
		self.lista_Nodos.adicionar(nodo_14)
		self.ui.radioButton_16.hide()
		nodo_15 = Nodo(self.ui.radioButton_16)
		nodo_15.setId(15)
		self.lista_Nodos.adicionar(nodo_15)
		self.ui.radioButton_17.hide()
		nodo_16 = Nodo(self.ui.radioButton_17)
		nodo_16.setId(16)
		self.lista_Nodos.adicionar(nodo_16)
		self.ui.radioButton_18.hide()
		nodo_17 = Nodo(self.ui.radioButton_18)
		nodo_17.setId(17)
		self.lista_Nodos.adicionar(nodo_17)
		self.ui.radioButton_19.hide()
		nodo_18 = Nodo(self.ui.radioButton_19)
		nodo_18.setId(18)
		self.lista_Nodos.adicionar(nodo_18)
		self.ui.radioButton_20.hide()
		nodo_19 = Nodo(self.ui.radioButton_20)
		nodo_19.setId(19)
		self.lista_Nodos.adicionar(nodo_19)
		self.ui.radioButton_21.hide()
		nodo_20 = Nodo(self.ui.radioButton_21)
		nodo_20.setId(20)
		self.lista_Nodos.adicionar(nodo_20)
		self.ui.radioButton_22.hide()
		nodo_21 = Nodo(self.ui.radioButton_22)
		nodo_21.setId(21)
		self.lista_Nodos.adicionar(nodo_21)
		self.ui.radioButton_23.hide()
		nodo_22 = Nodo(self.ui.radioButton_23)
		nodo_22.setId(22)
		self.lista_Nodos.adicionar(nodo_22)
		self.ui.radioButton_24.hide()
		nodo_23 = Nodo(self.ui.radioButton_24)
		nodo_23.setId(23)
		self.lista_Nodos.adicionar(nodo_23)
		self.ui.radioButton_25.hide()
		nodo_24 = Nodo(self.ui.radioButton_25)
		nodo_24.setId(24)
		self.lista_Nodos.adicionar(nodo_24)
		self.ui.radioButton_26.hide()
		nodo_25 = Nodo(self.ui.radioButton_26)
		nodo_25.setId(25)
		self.lista_Nodos.adicionar(nodo_25)
		self.ui.radioButton_27.hide()
		nodo_26 = Nodo(self.ui.radioButton_27)
		nodo_26.setId(26)
		self.lista_Nodos.adicionar(nodo_26)
		self.ui.radioButton_28.hide()
		nodo_27 = Nodo(self.ui.radioButton_28)
		nodo_27.setId(27)
		self.lista_Nodos.adicionar(nodo_27)
		self.ui.radioButton_29.hide()
		nodo_28 = Nodo(self.ui.radioButton_29)
		nodo_28.setId(28)
		self.lista_Nodos.adicionar(nodo_28)
		self.ui.radioButton_30.hide()
		nodo_29 = Nodo(self.ui.radioButton_30)
		nodo_29.setId(29)
		self.lista_Nodos.adicionar(nodo_29)
		self.ui.radioButton_31.hide()
		nodo_30 = Nodo(self.ui.radioButton_31)
		nodo_30.setId(30)
		self.lista_Nodos.adicionar(nodo_30)
		self.ui.radioButton_32.hide()
		nodo_31 = Nodo(self.ui.radioButton_32)
		nodo_31.setId(31)
		self.lista_Nodos.adicionar(nodo_31)
		self.ui.radioButton_33.hide()
		nodo_32 = Nodo(self.ui.radioButton_33)
		nodo_32.setId(32)
		self.lista_Nodos.adicionar(nodo_32)
		self.ui.radioButton_34.hide()
		nodo_33 = Nodo(self.ui.radioButton_34)
		nodo_33.setId(33)
		self.lista_Nodos.adicionar(nodo_33)
		self.ui.radioButton_35.hide()
		nodo_34 = Nodo(self.ui.radioButton_35)
		nodo_34.setId(34)
		self.lista_Nodos.adicionar(nodo_34)
		self.ui.radioButton_36.hide()
		nodo_35 = Nodo(self.ui.radioButton_36)
		nodo_35.setId(35)
		self.lista_Nodos.adicionar(nodo_35)
		self.ui.radioButton_37.hide()
		nodo_36 = Nodo(self.ui.radioButton_37)
		nodo_36.setId(36)
		self.lista_Nodos.adicionar(nodo_36)
		self.ui.radioButton_38.hide()
		nodo_37 = Nodo(self.ui.radioButton_38)
		nodo_37.setId(37)
		self.lista_Nodos.adicionar(nodo_37)
		self.ui.radioButton_39.hide()
		nodo_38 = Nodo(self.ui.radioButton_39)
		nodo_38.setId(38)
		self.lista_Nodos.adicionar(nodo_38)
		self.ui.radioButton_40.hide()
		nodo_39 = Nodo(self.ui.radioButton_40)
		nodo_39.setId(39)
		self.lista_Nodos.adicionar(nodo_39)
		self.ui.radioButton_41.hide()
		nodo_40 = Nodo(self.ui.radioButton_41)
		nodo_40.setId(40)
		self.lista_Nodos.adicionar(nodo_40)
		self.ui.radioButton_42.hide()
		nodo_41 = Nodo(self.ui.radioButton_42)
		nodo_41.setId(41)
		self.lista_Nodos.adicionar(nodo_41)
		self.ui.radioButton_43.hide()
		nodo_42 = Nodo(self.ui.radioButton_43)
		nodo_42.setId(42)
		self.lista_Nodos.adicionar(nodo_42)
		self.ui.radioButton_44.hide()
		nodo_43 = Nodo(self.ui.radioButton_44)
		nodo_43.setId(43)
		self.lista_Nodos.adicionar(nodo_43)
		self.ui.radioButton_45.hide()
		nodo_44 = Nodo(self.ui.radioButton_45)
		nodo_44.setId(44)
		self.lista_Nodos.adicionar(nodo_44)
		self.ui.radioButton_46.hide()
		nodo_45 = Nodo(self.ui.radioButton_46)
		nodo_45.setId(45)
		self.lista_Nodos.adicionar(nodo_45)
		self.ui.radioButton_47.hide()
		nodo_46 = Nodo(self.ui.radioButton_47)
		nodo_46.setId(46)
		self.lista_Nodos.adicionar(nodo_46)
		self.ui.radioButton_48.hide()
		nodo_47 = Nodo(self.ui.radioButton_48)
		nodo_47.setId(47)
		self.lista_Nodos.adicionar(nodo_47)
		self.ui.radioButton_49.hide()
		nodo_48 = Nodo(self.ui.radioButton_49)
		nodo_48.setId(48)
		self.lista_Nodos.adicionar(nodo_48)
		self.ui.radioButton_50.hide()
		nodo_49 = Nodo(self.ui.radioButton_50)
		nodo_49.setId(49)
		self.lista_Nodos.adicionar(nodo_49)
		self.ui.radioButton_51.hide()
		nodo_50 = Nodo(self.ui.radioButton_51)
		nodo_50.setId(50)
		self.lista_Nodos.adicionar(nodo_50)
		self.ui.radioButton_52.hide()
		nodo_51 = Nodo(self.ui.radioButton_52)
		nodo_51.setId(51)
		self.lista_Nodos.adicionar(nodo_51)
		self.ui.radioButton_53.hide()
		nodo_52 = Nodo(self.ui.radioButton_53)
		nodo_52.setId(52)
		self.lista_Nodos.adicionar(nodo_52)
		self.ui.radioButton_54.hide()
		nodo_53 = Nodo(self.ui.radioButton_54)
		nodo_53.setId(53)
		self.lista_Nodos.adicionar(nodo_53)
		self.ui.radioButton_55.hide()
		nodo_54 = Nodo(self.ui.radioButton_55)
		nodo_54.setId(54)
		self.lista_Nodos.adicionar(nodo_54)
		self.ui.radioButton_56.hide()
		nodo_55 = Nodo(self.ui.radioButton_56)
		nodo_55.setId(55)
		self.lista_Nodos.adicionar(nodo_55)
		self.ui.radioButton_57.hide()
		nodo_56 = Nodo(self.ui.radioButton_57)
		nodo_56.setId(56)
		self.lista_Nodos.adicionar(nodo_56)
		self.ui.radioButton_58.hide()
		nodo_57 = Nodo(self.ui.radioButton_58)
		nodo_57.setId(57)
		self.lista_Nodos.adicionar(nodo_57)
		self.ui.radioButton_59.hide()
		nodo_58 = Nodo(self.ui.radioButton_59)
		nodo_58.setId(58)
		self.lista_Nodos.adicionar(nodo_58)
		self.ui.radioButton_60.hide()
		nodo_59 = Nodo(self.ui.radioButton_60)
		nodo_59.setId(59)
		self.lista_Nodos.adicionar(nodo_59)
		self.ui.radioButton_61.hide()
		nodo_60 = Nodo(self.ui.radioButton_61)
		nodo_60.setId(60)
		self.lista_Nodos.adicionar(nodo_60)
		self.ui.radioButton_62.hide()
		nodo_61 = Nodo(self.ui.radioButton_62)
		nodo_61.setId(61)
		self.lista_Nodos.adicionar(nodo_61)
		self.ui.radioButton_63.hide()
		nodo_62 = Nodo(self.ui.radioButton_63)
		nodo_62.setId(62)
		self.lista_Nodos.adicionar(nodo_62)
		self.ui.radioButton_64.hide()
		nodo_63 = Nodo(self.ui.radioButton_64)
		nodo_63.setId(63)
		self.lista_Nodos.adicionar(nodo_63)
		self.ui.radioButton_65.hide()
		nodo_64 = Nodo(self.ui.radioButton_65)
		nodo_64.setId(64)
		self.lista_Nodos.adicionar(nodo_64)
		self.ui.radioButton_66.hide()
		nodo_65 = Nodo(self.ui.radioButton_66)
		nodo_65.setId(65)
		self.lista_Nodos.adicionar(nodo_65)
		self.ui.radioButton_67.hide()
		nodo_66 = Nodo(self.ui.radioButton_67)
		nodo_66.setId(66)
		self.lista_Nodos.adicionar(nodo_66)
		self.ui.radioButton_68.hide()
		nodo_67 = Nodo(self.ui.radioButton_68)
		nodo_67.setId(67)
		self.lista_Nodos.adicionar(nodo_67)
		self.ui.radioButton_69.hide()
		nodo_68 = Nodo(self.ui.radioButton_69)
		nodo_68.setId(68)
		self.lista_Nodos.adicionar(nodo_68)
		self.ui.radioButton_70.hide()
		nodo_69 = Nodo(self.ui.radioButton_70)
		nodo_69.setId(69)
		self.lista_Nodos.adicionar(nodo_69)
		self.ui.radioButton_71.hide()
		nodo_70 = Nodo(self.ui.radioButton_71)
		nodo_70.setId(70)
		self.lista_Nodos.adicionar(nodo_70)
		self.ui.radioButton_72.hide()
		nodo_71 = Nodo(self.ui.radioButton_72)
		nodo_71.setId(71)
		self.lista_Nodos.adicionar(nodo_71)
		self.ui.radioButton_73.hide()
		nodo_72 = Nodo(self.ui.radioButton_73)
		nodo_72.setId(72)
		self.lista_Nodos.adicionar(nodo_72)
		self.ui.radioButton_74.hide()
		nodo_73 = Nodo(self.ui.radioButton_74)
		nodo_73.setId(73)
		self.lista_Nodos.adicionar(nodo_73)
		self.ui.radioButton_75.hide()
		nodo_74 = Nodo(self.ui.radioButton_75)
		nodo_74.setId(74)
		self.lista_Nodos.adicionar(nodo_74)
		self.ui.radioButton_76.hide()
		nodo_75 = Nodo(self.ui.radioButton_76)
		nodo_75.setId(75)
		self.lista_Nodos.adicionar(nodo_75)
		self.ui.radioButton_77.hide()
		nodo_76 = Nodo(self.ui.radioButton_77)
		nodo_76.setId(76)
		self.lista_Nodos.adicionar(nodo_76)
		self.ui.radioButton_78.hide()
		nodo_77 = Nodo(self.ui.radioButton_78)
		nodo_77.setId(77)
		self.lista_Nodos.adicionar(nodo_77)
		self.ui.radioButton_79.hide()
		nodo_78 = Nodo(self.ui.radioButton_79)
		nodo_78.setId(78)
		self.lista_Nodos.adicionar(nodo_78)
		self.ui.radioButton_80.hide()
		nodo_79 = Nodo(self.ui.radioButton_80)
		nodo_79.setId(79)
		self.lista_Nodos.adicionar(nodo_79)
		self.ui.radioButton_81.hide()
		nodo_80 = Nodo(self.ui.radioButton_81)
		nodo_80.setId(80)
		self.lista_Nodos.adicionar(nodo_80)
		self.ui.radioButton_82.hide()
		nodo_81 = Nodo(self.ui.radioButton_82)
		nodo_81.setId(81)
		self.lista_Nodos.adicionar(nodo_81)
		self.ui.radioButton_83.hide()
		nodo_82 = Nodo(self.ui.radioButton_83)
		nodo_82.setId(82)
		self.lista_Nodos.adicionar(nodo_82)
		self.ui.radioButton_84.hide()
		nodo_83 = Nodo(self.ui.radioButton_84)
		nodo_83.setId(83)
		self.lista_Nodos.adicionar(nodo_83)
		self.ui.radioButton_85.hide()
		nodo_84 = Nodo(self.ui.radioButton_85)
		nodo_84.setId(84)
		self.lista_Nodos.adicionar(nodo_84)
		self.ui.radioButton_86.hide()
		nodo_85 = Nodo(self.ui.radioButton_86)
		nodo_85.setId(85)
		self.lista_Nodos.adicionar(nodo_85)
		self.ui.radioButton_87.hide()
		nodo_86 = Nodo(self.ui.radioButton_87)
		nodo_86.setId(86)
		self.lista_Nodos.adicionar(nodo_86)
		self.ui.radioButton_88.hide()
		nodo_87 = Nodo(self.ui.radioButton_88)
		nodo_87.setId(87)
		self.lista_Nodos.adicionar(nodo_87)
		self.ui.radioButton_89.hide()
		nodo_88 = Nodo(self.ui.radioButton_89)
		nodo_88.setId(88)
		self.lista_Nodos.adicionar(nodo_88)
		self.ui.radioButton_90.hide()
		nodo_89 = Nodo(self.ui.radioButton_90)
		nodo_89.setId(89)
		self.lista_Nodos.adicionar(nodo_89)
		self.ui.radioButton_91.hide()
		nodo_90 = Nodo(self.ui.radioButton_91)
		nodo_90.setId(90)
		self.lista_Nodos.adicionar(nodo_90)
		self.ui.radioButton_92.hide()
		nodo_91 = Nodo(self.ui.radioButton_92)
		nodo_91.setId(91)
		self.lista_Nodos.adicionar(nodo_91)
		self.ui.radioButton_93.hide()
		nodo_92 = Nodo(self.ui.radioButton_93)
		nodo_92.setId(92)
		self.lista_Nodos.adicionar(nodo_92)
		self.ui.radioButton_94.hide()
		nodo_93 = Nodo(self.ui.radioButton_94)
		nodo_93.setId(93)
		self.lista_Nodos.adicionar(nodo_93)
		self.ui.radioButton_95.hide()
		nodo_94 = Nodo(self.ui.radioButton_95)
		nodo_94.setId(94)
		self.lista_Nodos.adicionar(nodo_94)
		self.ui.radioButton_96.hide()
		nodo_95 = Nodo(self.ui.radioButton_96)
		nodo_95.setId(95)
		self.lista_Nodos.adicionar(nodo_95)
		self.ui.radioButton_97.hide()
		nodo_96 = Nodo(self.ui.radioButton_97)
		nodo_96.setId(96)
		self.lista_Nodos.adicionar(nodo_96)
		self.ui.radioButton_98.hide()
		nodo_97 = Nodo(self.ui.radioButton_98)
		nodo_97.setId(97)
		self.lista_Nodos.adicionar(nodo_97)
		self.ui.radioButton_99.hide()
		nodo_98 = Nodo(self.ui.radioButton_99)
		nodo_98.setId(98)
		self.lista_Nodos.adicionar(nodo_98)

	def adicionar_Nodo_Inicio(self):
		self.ui.pushButton_6.setEnabled(True)
		self.ui.pushButton_7.setEnabled(True)
		self.lista_Nodos.get_nodo(self.cont_lista_Nodos_Inicio).adicionar_Nodo()
		self.cont_lista_Nodos_Inicio += 1
		if self.cont_lista_Nodos_Inicio == 8:
			self.ui.pushButton_5.setEnabled(False)

	def eliminar_Nodo_Inicio(self):
		self.cont_lista_Nodos_Inicio -= 1
		self.lista_Nodos.get_nodo(self.cont_lista_Nodos_Inicio).eliminar_Nodo()
		if self.cont_lista_Nodos_Inicio < 8:
			self.ui.pushButton_5.setEnabled(True)
		if self.cont_lista_Nodos_Inicio == 0:
			self.ui.pushButton_6.setEnabled(False)
			self.ui.pushButton_7.setEnabled(False)

	def adicionar_Nodo_Proceso(self):
		if self.flag_1 == True:
			self.ui.pushButton_9.setEnabled(True)
			self.flag_1 = False
		self.ui.pushButton_8.setEnabled(True)
		self.lista_Nodos.get_nodo(self.lista_Capas_Nodos_Proceso[self.cont_Capa_Proceso][self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso]]).adicionar_Nodo()
		self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso] += 1
		if self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso] == 8:
			self.ui.pushButton_7.setEnabled(False)

	def eliminar_Nodo_Proceso(self):
		self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso] -= 1
		self.lista_Nodos.get_nodo(self.lista_Capas_Nodos_Proceso[self.cont_Capa_Proceso][self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso]]).eliminar_Nodo()
		if self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso] < 8:
			self.ui.pushButton_7.setEnabled(True)
		if self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso] == 0:
			self.ui.pushButton_8.setEnabled(False)

	def adicionar_Capa_Proceso(self):
		self.ui.pushButton.setEnabled(True)
		self.cont_Capa_Proceso += 1
		self.lista_Nodos.get_nodo(self.lista_Capas_Nodos_Proceso[self.cont_Capa_Proceso][self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso]]).adicionar_Nodo()
		self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso] += 1
		if self.cont_Capa_Proceso == 9:
			self.ui.pushButton_9.setEnabled(False)

	def eliminar_Capa_Proceso(self):
		if self.cont_Capa_Proceso < 10:
			self.ui.pushButton_9.setEnabled(True)
		while True:
			if self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso] == 0:
				self.lista_Nodos.get_nodo(self.lista_Capas_Nodos_Proceso[self.cont_Capa_Proceso][self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso]]).eliminar_Nodo()
				break
			if self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso] != 0:
				self.lista_Nodos.get_nodo(self.lista_Capas_Nodos_Proceso[self.cont_Capa_Proceso][self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso]]).eliminar_Nodo()
				self.list_cont_por_Nodos_Proceso[self.cont_Capa_Proceso] -= 1
		self.cont_Capa_Proceso -= 1
		if self.cont_Capa_Proceso == 0:
			self.ui.pushButton.setEnabled(False)
			
class Nodo(object):
	def __init__(self, radioButton:QRadioButton):
		self.id_Nodo:int
		self.radio_Button = radioButton
	
	def setId(self, id_int:int):
		self.id_Nodo = id_int
	
	def getId(self):
		return self.id_Nodo

	def adicionar_Nodo(self):
		self.radio_Button.show()
	
	def eliminar_Nodo(self):
		self.radio_Button.hide()

class Lista_Nodos(object):
	def __init__(self):
		self.lista = []

	def get_nodo(self, i:int):
		return self.lista[i]
	
	def adicionar(self, nodo):
		self.lista.append(nodo)





